#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

msg=`cat "$1"`

#match conventional emoji pattern ':emoji: type(scope): short description'

if [[ "$msg" =~ ^(:[a-z0-9_-]+:)+[[:space:]](feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\([a-z0-9_\-]+\):[[:space:]].+$ ]]; then

    echo "\n✅ Valid commit message\n"

else

    echo "\n❌ Invalid commit message, use 'yarn commit' or follow conventional commits ':emoji: type(scope): short description'\n" && exit 1

fi
